/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || 'no-api-key-set';
config.sitecoreApiHost = process.env.SITECORE_API_HOST || '';
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'AstroApp';
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge';
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en';
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || '/sitecore/api/graph/edge';
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'default';
config.publicUrl = process.env.PUBLIC_URL || '';
config.sitecoreEdgeUrl = process.env.SITECORE_EDGE_URL || 'http://127.0.0.1:3200';
config.sitecoreEdgeContextId = process.env.SITECORE_EDGE_CONTEXT_ID || 'test';
config.sites = process.env.SITES || '[{"name":"Test1","hostName":"*","language":"en"}]';
export default config;