/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || '{ADCF0159-031F-4093-9DDA-45FF14C81989}';
config.sitecoreApiHost = process.env.SITECORE_API_HOST || 'https://xmcloudcm.localhost';
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'AstroApp';
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge';
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en';
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://xmcloudcm.localhost/sitecore/api/graph/edge';
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'default';
config.publicUrl = process.env.PUBLIC_URL || 'undefined';
config.sitecoreEdgeUrl = process.env.SITECORE_EDGE_URL || 'https://edge-platform.sitecorecloud.io';
config.sitecoreEdgeContextId = process.env.SITECORE_EDGE_CONTEXT_ID || '';
config.sites = process.env.SITES || '[]';
export default config;